### ISSUE TITLE
Really interesting the way you’re using GitHub with drummer

### ISSUE THREAD

**Issue by scripting** [alexjj/drummer-blog#2]
😀

**Comment by alexjj** [comment]
Microsoft provides all this infrastructure for free, be a shame not to use it. 😅

**Comment by scripting** [comment]
Yes!

**Comment by scripting** [comment]
Btw, not sure if you’ve seen the way I use a repo to archive my blog. 

https://github.com/scripting/Scripting-News/tree/master/blog

The archive goes back to may 2017.
